# Generated by Django 6.0 on 2025-12-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sac_academia", "0002_mensagem_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagem",
            name="lida",
            field=models.BooleanField(default=False),
        ),
    ]
